# Generated by Django 4.2.2 on 2023-06-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='mode',
            field=models.IntegerField(choices=[(0, 'idle'), (1, 'edit'), (2, 'result'), (3, 'answer')], default=0),
        ),
    ]
