# Generated by Django 4.2.2 on 2023-07-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_exam_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='mode',
            field=models.IntegerField(choices=[(0, 'idle'), (1, 'edit'), (2, 'result'), (3, 'answer'), (4, 'grading')], default=0),
        ),
    ]
