# Generated by Django 4.2.2 on 2023-06-29 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=2048)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_model_answer', to='question.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeyPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_index', models.IntegerField(null=True)),
                ('end_index', models.IntegerField(null=True)),
                ('grade', models.FloatField(default=0)),
                ('model_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_answer_key_phrases', to='model_answer.modelanswer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='keyphrase',
            constraint=models.CheckConstraint(check=models.Q(('end_index__gt', models.F('start_index'))), name='end_index_gt_start_index'),
        ),
    ]
