# Generated by Django 4.2.2 on 2023-06-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        ('model_answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelanswer',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_model_answer', to='question.question'),
        ),
    ]
