# Generated by Django 4.2.2 on 2023-06-29 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('model_answer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_model_answer', to='question.question'),
        ),
        migrations.AddField(
            model_name='keyphrase',
            name='model_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_answer_key_phrases', to='model_answer.modelanswer'),
        ),
        migrations.AddConstraint(
            model_name='keyphrase',
            constraint=models.CheckConstraint(check=models.Q(('end_index__gt', models.F('start_index'))), name='end_index_gt_start_index'),
        ),
    ]
