# Generated by Django 4.2.2 on 2023-06-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_answer', '0002_alter_modelanswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelanswer',
            name='question',
        ),
    ]
