# Generated by Django 4.2.2 on 2023-07-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_answer', '0003_remove_modelanswer_question'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keyphrase',
            name='end_index_gt_start_index',
        ),
        migrations.AddConstraint(
            model_name='keyphrase',
            constraint=models.CheckConstraint(check=models.Q(('end_index__gt', models.F('start_index'))), name='model_answer_end_index_gt_start_index'),
        ),
    ]
