# Generated by Django 4.2.2 on 2023-06-29 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model_answer', '0001_initial'),
        ('student_answer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_grade', models.FloatField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_answer.answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerConfidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.FloatField()),
                ('grade', models.FloatField()),
                ('answer_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.answergrade')),
                ('key_phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_answer.keyphrase')),
            ],
        ),
        migrations.AddConstraint(
            model_name='answerconfidence',
            constraint=models.UniqueConstraint(fields=('answer_grade', 'key_phrase'), name='unique_answer_grade_and_key_phrase_together'),
        ),
    ]
