# Generated by Django 4.2.2 on 2023-07-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0009_answer_total_grade'),
        ('grade', '0002_answersegment_remove_answergrade_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersegment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_segments', to='student_answer.answer'),
        ),
    ]
