# Generated by Django 4.2.2 on 2023-06-29 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_answer', '0003_remove_modelanswer_question'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='model_answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_answer', to='model_answer.modelanswer'),
        ),
    ]
