# Generated by Django 4.2.2 on 2023-06-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0003_alter_answer_student_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='student_id',
            field=models.CharField(max_length=32),
        ),
    ]
