# Generated by Django 4.2.2 on 2023-06-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0004_alter_studentanswer_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='student_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answer_id', to='student_answer.studentanswer'),
        ),
    ]
