# Generated by Django 4.2.2 on 2023-06-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0005_studentanswer_is_submitted_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together=set(),
        ),
    ]
