# Generated by Django 4.2.2 on 2023-07-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0006_alter_studentanswer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
