# Generated by Django 4.2.2 on 2023-07-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0008_alter_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='total_grade',
            field=models.FloatField(default=0),
        ),
    ]
